export const tierData = [
  {
    title: 'A',
    difficulty: 'ANOTHER',
    normal: 'ep F',
    hard: 'ep F',
    version: '7',
  },
  {
    title: 'AA',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '11',
  },
  {
    title: 'AA -rebuild-',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '25',
  },
  {
    title: 'ABSOLUTE EVIL',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '29',
  },
  {
    title: 'Adularia',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'id C',
    version: '21',
  },
  {
    title: 'Aftermath',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '29',
  },
  {
    title: 'AIR RAID FROM THA UNDAGROUND',
    difficulty: 'LEGGENDARIA',
    normal: 'id A',
    hard: 'id B+',
    version: '21',
  },
  {
    title: 'AKASHIC BREAK',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '27',
  },
  {
    title: 'ALBIDA',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '18',
  },
  {
    title: 'Almagest',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep S',
    version: '17',
  },
  {
    title: 'ALTERNATOR',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A+',
    version: '29',
  },
  {
    title: 'Amazing Mirage',
    difficulty: 'LEGGENDARIA',
    normal: 'ep C',
    hard: 'ep B',
    version: '24',
  },
  {
    title: 'ANCHOR',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep A',
    version: '25',
  },
  {
    title: 'Ancient Scapes',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '21',
  },
  {
    title: 'Ancient Scapes',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '21',
  },
  {
    title: "Angel's Ladder",
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '29',
  },
  {
    title: 'Anisakis-somatic mutation type "Forza"-',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '15',
  },
  {
    title: 'anthracene',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B+',
    version: '30',
  },
  {
    title: 'Antigravity',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'id A',
    version: '25',
  },
  {
    title: 'AO-1',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'ep B',
    version: '23',
  },
  {
    title: 'Apocalypse',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '24',
  },
  {
    title: 'Arabian Rave Night',
    difficulty: 'LEGGENDARIA',
    normal: 'ep C',
    hard: 'ep B',
    version: '16',
  },
  {
    title: 'Arca',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '25',
  },
  {
    title: 'Arkadia',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '29',
  },
  {
    title: 'Artist',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '27',
  },
  {
    title: 'ASIAN VIRTUAL REALITIES (MELTING TOGETHER IN DAZZLING DARKNESS)',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '28',
  },
  {
    title: 'B.O.D.Y.',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'id C',
    version: '30',
  },
  {
    title: 'B4U(BEMANI FOR YOU MIX)',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '16',
  },
  {
    title: 'Bad Encryption',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep S',
    version: '30',
  },
  {
    title: 'Bad Maniacs',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '17',
  },
  {
    title: 'Be quiet',
    difficulty: 'LEGGENDARIA',
    normal: 'id B+',
    hard: 'id A+',
    version: '11',
  },
  {
    title: 'BEAT PRISONER',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '27',
  },
  {
    title: 'Beat Radiance',
    difficulty: 'LEGGENDARIA',
    normal: 'ep D',
    hard: 'ep D',
    version: '22',
  },
  {
    title: 'Beyond Evolution',
    difficulty: 'ANOTHER',
    normal: 'ep S+',
    hard: 'ep S+',
    version: '30',
  },
  {
    title: 'BIGソムタム',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep E',
    version: '28',
  },
  {
    title: 'BIGWAVERS',
    difficulty: 'ANOTHER',
    normal: '',
    hard: '',
    version: '30',
  },
  {
    title: 'Binary Black Hole',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '29',
  },
  {
    title: 'BITTER CHOCOLATE STRIKER',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '16',
  },
  {
    title: 'BLACK or WHITE?',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '28',
  },
  {
    title: 'BLACK.by X-Cross Fade',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id S',
    version: '19',
  },
  {
    title: 'BLUE DRAGON(雷龍RemixIIDX)',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '21',
  },
  {
    title: 'BLUE MIRAGE',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'id A',
    version: '22',
  },
  {
    title: 'Blue Rain',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep A',
    version: '15',
  },
  {
    title: 'Blue Spring Express',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '23',
  },
  {
    title: 'Boomy and The Boost',
    difficulty: 'ANOTHER',
    normal: 'id B+',
    hard: 'ep A',
    version: '25',
  },
  {
    title: 'BroGamer',
    difficulty: 'LEGGENDARIA',
    normal: 'id S',
    hard: 'ep S',
    version: '24',
  },
  {
    title: 'Broken',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '18',
  },
  {
    title: 'Broken Sword',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '22',
  },
  {
    title: 'Burning Flame',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B',
    hard: 'ep B+',
    version: '28',
  },
  {
    title: 'Candy Galy',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep C',
    version: '14',
  },
  {
    title: 'Carmina',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '26',
  },
  {
    title: 'Carry Me Away',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep D',
    version: '26',
  },
  {
    title: 'Catch Our Fire!',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '26',
  },
  {
    title: 'Caterpillar',
    difficulty: 'ANOTHER',
    normal: 'id D',
    hard: 'id C',
    version: '24',
  },
  {
    title: 'Chaotoxin',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '30',
  },
  {
    title: 'CHRONO DIVER -NORNIR-',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '22',
  },
  {
    title: 'Chrono Diver -PENDULUMs-',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S+',
    version: '22',
  },
  {
    title: 'cinder',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '22',
  },
  {
    title: 'Close the World feat.a☆ru',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '21',
  },
  {
    title: 'Close the World feat.a☆ru',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep A',
    version: '21',
  },
  {
    title: 'CODE:1 [revision1.0.1]',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '23',
  },
  {
    title: 'Colorful Cookie',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '16',
  },
  {
    title: 'Colors(radio edit)',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep C',
    version: '6',
  },
  {
    title: 'Concertino in Blue',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep D',
    version: '13',
  },
  {
    title: 'Confiserie',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '20',
  },
  {
    title: 'CONTRACT',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '13',
  },
  {
    title: 'Cosmic Cat',
    difficulty: 'LEGGENDARIA',
    normal: 'ep C',
    hard: 'ep B',
    version: '22',
  },
  {
    title: 'COSMIC RAY',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '28',
  },
  {
    title: 'Dances with Snow Fairies',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '18',
  },
  {
    title: "Dans la nuit de l'eternite",
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep S',
    version: '27',
  },
  {
    title: 'DARK LEGACY',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '21',
  },
  {
    title: 'dAuntl3ss',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep D',
    version: '26',
  },
  {
    title: 'DAY DREAM',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'id A',
    version: '20',
  },
  {
    title: 'DEADHEAT',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '25',
  },
  {
    title: 'DEATH†ZIGOQ～怒りの高速爆走野郎～',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A+',
    version: '25',
  },
  {
    title: 'Despair of ELFERIA',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '22',
  },
  {
    title: "Devil's Gear",
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '23',
  },
  {
    title: 'Devilz Staircase',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '20',
  },
  {
    title: 'DIAMOND CROSSING',
    difficulty: 'ANOTHER',
    normal: 'id B+',
    hard: 'id A+',
    version: '23',
  },
  {
    title: 'DIAVOLO',
    difficulty: 'ANOTHER',
    normal: 'id S+',
    hard: 'id S+',
    version: '19',
  },
  {
    title: 'dica dica',
    difficulty: 'ANOTHER',
    normal: 'id D',
    hard: 'id C',
    version: '30',
  },
  {
    title: 'DOMINION',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '17',
  },
  {
    title: "Don't believe the hype",
    difficulty: 'ANOTHER',
    normal: 'id A',
    hard: 'id A+',
    version: '29',
  },
  {
    title: 'DORNWALD ～Junge～',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '24',
  },
  {
    title: 'Double Dribble',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '27',
  },
  {
    title: 'Dr. Chemical & Killing Machine',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '26',
  },
  {
    title: 'Drastic Dramatic',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '26',
  },
  {
    title: 'DropZ-Line-',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '25',
  },
  {
    title: 'DRUNK MONKY',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '26',
  },
  {
    title: 'DUAL STRIKER',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '28',
  },
  {
    title: 'DUE TOMORROW',
    difficulty: 'ANOTHER',
    normal: 'id E',
    hard: 'id C',
    version: '13',
  },
  {
    title: 'Dynamite',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'id A+',
    version: '23',
  },
  {
    title: 'EBONY & IVORY',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '22',
  },
  {
    title: 'EBONY & IVORY',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A+',
    hard: 'ep S',
    version: '22',
  },
  {
    title: 'ECHIDNA',
    difficulty: 'ANOTHER',
    normal: 'id S',
    hard: 'id S',
    version: '24',
  },
  {
    title: 'Elektrick U-Phoria',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep A+',
    version: '21',
  },
  {
    title: 'Elemental Creation',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '20',
  },
  {
    title: 'EMERALDAS',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '25',
  },
  {
    title: 'Empire of Fury',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep A',
    version: '28',
  },
  {
    title: 'encounter',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '25',
  },
  {
    title: 'entelecheia',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep C',
    version: '22',
  },
  {
    title: 'eRAseRmOToRpHAntOM',
    difficulty: 'ANOTHER',
    normal: 'id D',
    hard: 'id D',
    version: '17',
  },
  {
    title: 'EROICA',
    difficulty: 'ANOTHER',
    normal: 'id S',
    hard: 'ep S+',
    version: '27',
  },
  {
    title: 'EVANESCENT',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '26',
  },
  {
    title: 'Evans',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '17',
  },
  {
    title: 'Everlasting Message',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '27',
  },
  {
    title: 'EXUSIA',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep B+',
    version: '17',
  },
  {
    title: 'F',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '19',
  },
  {
    title: 'FAKE TIME',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'id C',
    version: '11',
  },
  {
    title: 'fallen leaves -IIDX edition-',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep A',
    version: '22',
  },
  {
    title: 'FANTASTIC THREE',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'id B',
    version: '22',
  },
  {
    title: 'Fascination MAXX',
    difficulty: 'ANOTHER',
    normal: 'id D',
    hard: 'id S',
    version: '14',
  },
  {
    title: 'Feel The Beat',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '21',
  },
  {
    title: 'Feel The Beat',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep S+',
    version: '21',
  },
  {
    title: 'Fegrix',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '29',
  },
  {
    title: 'fffff',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '19',
  },
  {
    title: 'Fire Beat',
    difficulty: 'ANOTHER',
    normal: 'id D',
    hard: 'id D',
    version: '28',
  },
  {
    title: 'FIRE FIRE',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '14',
  },
  {
    title: 'Flashes',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'ep A',
    version: '22',
  },
  {
    title: 'Flying Castle',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '29',
  },
  {
    title: 'four pieces of heaven',
    difficulty: 'LEGGENDARIA',
    normal: '',
    hard: '',
    version: '15',
  },
  {
    title: 'Friction[!]Function',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '27',
  },
  {
    title: 'FUZIN RIZIN',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '24',
  },
  {
    title: 'G59',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep B+',
    version: '17',
  },
  {
    title: 'GAIA',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '20',
  },
  {
    title: 'Ganymede',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep A+',
    version: '13',
  },
  {
    title: 'GENE',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '26',
  },
  {
    title: 'gigadelic',
    difficulty: 'HYPER',
    normal: 'ep E',
    hard: 'ep F',
    version: '11',
  },
  {
    title: 'gigadelic',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep F',
    version: '11',
  },
  {
    title: 'GiGaGaHell',
    difficulty: 'ANOTHER',
    normal: 'id B+',
    hard: 'id A+',
    version: '29',
  },
  {
    title: 'glacia',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '30',
  },
  {
    title: 'Go Ahead!!',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S+',
    version: '24',
  },
  {
    title: 'Go Beyond!!',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep S+',
    version: '16',
  },
  {
    title: 'GO OVER WITH GLARE -ROOTAGE 26-',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '26',
  },
  {
    title: 'Godspeed',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B+',
    version: '23',
  },
  {
    title: 'GOLDEN CROSS',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '17',
  },
  {
    title: 'Grand Chariot',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '23',
  },
  {
    title: 'Gravigazer',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '22',
  },
  {
    title: 'GRAVITON',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '29',
  },
  {
    title: 'GRID KNIGHT',
    difficulty: 'LEGGENDARIA',
    normal: 'id E',
    hard: 'ep E',
    version: '14',
  },
  {
    title: 'GuNGNiR',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A+',
    version: '24',
  },
  {
    title: 'GuNGNiR',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S+',
    hard: 'ep S+',
    version: '24',
  },
  {
    title: 'HADES',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep B+',
    version: '24',
  },
  {
    title: 'HAERETICUS',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '19',
  },
  {
    title: 'HARD BRAIN',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep C',
    version: '26',
  },
  {
    title: 'hard-wired',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '29',
  },
  {
    title: 'Hat Surprise (Season 2)',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '30',
  },
  {
    title: 'Highcharge Divolt',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '23',
  },
  {
    title: 'Hollywood Galaxy',
    difficulty: 'ANOTHER',
    normal: 'id B+',
    hard: 'ep A',
    version: '20',
  },
  {
    title: 'I',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '30',
  },
  {
    title: 'ICARUS',
    difficulty: 'ANOTHER',
    normal: 'id E',
    hard: 'id D',
    version: '15',
  },
  {
    title: 'ICARUS',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S',
    hard: 'ep S+',
    version: '15',
  },
  {
    title: 'Idola',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '21',
  },
  {
    title: 'Ignis†Iræ',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep S',
    version: '28',
  },
  {
    title: 'Illegal Function Call',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S+',
    hard: 'ep S+',
    version: '20',
  },
  {
    title: 'Illusionary Waterlily',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '25',
  },
  {
    title: 'IMPLANTATION',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'id B',
    version: '22',
  },
  {
    title: 'Inferno of Fomalhaut',
    difficulty: 'ANOTHER',
    normal: 'id B+',
    hard: 'id A',
    version: '27',
  },
  {
    title: 'Initiation',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '25',
  },
  {
    title: 'innocent revolver',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '28',
  },
  {
    title: 'Innocent Walls',
    difficulty: 'HYPER',
    normal: 'id E',
    hard: 'id E',
    version: '10',
  },
  {
    title: 'Innocent Walls',
    difficulty: 'ANOTHER',
    normal: 'id E',
    hard: 'id D',
    version: '10',
  },
  {
    title: 'INSOMNIA',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '21',
  },
  {
    title: 'Invitation from Mr.C',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'id B',
    version: '22',
  },
  {
    title: 'invoker',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '21',
  },
  {
    title: 'invoker',
    difficulty: 'LEGGENDARIA',
    normal: 'id A+',
    hard: 'ep A+',
    version: '21',
  },
  {
    title: 'JOMANDA',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'id A',
    version: '20',
  },
  {
    title: 'KAISER PHOENIX',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A+',
    version: '21',
  },
  {
    title: 'KAISER PHOENIX',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S',
    hard: 'ep S+',
    version: '21',
  },
  {
    title: 'KAMAITACHI',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S+',
    hard: 'ep S+',
    version: '14',
  },
  {
    title: 'KILL EACH OTHER',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '26',
  },
  {
    title: 'Konzert V',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '23',
  },
  {
    title: "kors k's How to make OTOGE CORE 「LONG」",
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep A',
    version: '30',
  },
  {
    title: 'Kung-fu Empire',
    difficulty: 'LEGGENDARIA',
    normal: 'ep D',
    hard: 'ep C',
    version: '16',
  },
  {
    title: 'L.F.O',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '26',
  },
  {
    title: 'LASER CRUSTER',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '14',
  },
  {
    title: 'LASER CRUSTER (IGNITE REMIX)',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '27',
  },
  {
    title: 'Last Dance',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '21',
  },
  {
    title: 'Lethal Weapon',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '26',
  },
  {
    title: 'Level One',
    difficulty: 'ANOTHER',
    normal: 'id A',
    hard: 'id S',
    version: '26',
  },
  {
    title: 'Level 2',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'id B+',
    version: '27',
  },
  {
    title: 'Level 3',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id S',
    version: '28',
  },
  {
    title: 'Level 4',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id S',
    version: '30',
  },
  {
    title: 'Liberation',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep D',
    version: '20',
  },
  {
    title: 'Life Is A Game ft.DD"ナカタ"Metal',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '25',
  },
  {
    title: 'LIGHTNING STRIKES',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '27',
  },
  {
    title: 'Little Little Princess',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B',
    hard: 'ep B',
    version: '12',
  },
  {
    title: 'Little Star',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '20',
  },
  {
    title: 'LIVE DRIVING!! feat. 花たん',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '29',
  },
  {
    title: 'LOCUS OF THE TRAVEL',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A+',
    version: '28',
  },
  {
    title: 'Lords Of The Roundtable',
    difficulty: 'ANOTHER',
    normal: 'id S',
    hard: 'id S',
    version: '27',
  },
  {
    title: 'LOST TECHNOLOGIE',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '26',
  },
  {
    title: 'LOUDER ROLLING THUNDER',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '30',
  },
  {
    title: 'M4K3 1T B0UNC3',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep C',
    version: '23',
  },
  {
    title: 'Mächö Mönky',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep A',
    version: '26',
  },
  {
    title: 'Mare Nectaris',
    difficulty: 'ANOTHER',
    normal: 'ep S+',
    hard: 'ep S+',
    version: '24',
  },
  {
    title: 'Marie Antoinette',
    difficulty: 'LEGGENDARIA',
    normal: 'id B',
    hard: 'id B',
    version: '16',
  },
  {
    title: 'Matt Silver',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '27',
  },
  {
    title: 'MAX 300',
    difficulty: 'ANOTHER',
    normal: '',
    hard: '',
    version: '7',
  },
  {
    title: 'MEGAERA',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '28',
  },
  {
    title: 'Megalara Garuda',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '27',
  },
  {
    title: 'MENDES',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '15',
  },
  {
    title: 'Meissa',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '30',
  },
  {
    title: 'Monopole.',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '22',
  },
  {
    title: 'moon_child',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '9',
  },
  {
    title: 'mosaic',
    difficulty: 'ANOTHER',
    normal: 'id D',
    hard: 'id E',
    version: '17',
  },
  {
    title: 'n/a',
    difficulty: 'ANOTHER',
    normal: 'ep S+',
    hard: 'ep S+',
    version: '29',
  },
  {
    title: 'No Border',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '30',
  },
  {
    title: 'NEO GENERATOR SEVEN',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '22',
  },
  {
    title: 'neu',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '20',
  },
  {
    title: 'New Castle Legions',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'id B',
    version: '18',
  },
  {
    title: 'NEW GENERATION-もう、お前しか見えない-',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B+',
    hard: 'ep A',
    version: '15',
  },
  {
    title: 'Nightmare before oversleep',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '23',
  },
  {
    title: 'NINJA IS DEAD IIDX ver.',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '23',
  },
  {
    title: 'NITROUS CANNON',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '25',
  },
  {
    title: 'NNRT',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '19',
  },
  {
    title: 'NZM',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'id S',
    version: '23',
  },
  {
    title: 'ONE AND ONLY',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '30',
  },
  {
    title: 'One for All',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '29',
  },
  {
    title: 'One More Lovely',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep C',
    version: '10',
  },
  {
    title: 'one or eight',
    difficulty: 'ANOTHER',
    normal: 'id E',
    hard: 'id D',
    version: '9',
  },
  {
    title: 'ONIGOROSHI',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'id B',
    version: '26',
  },
  {
    title: 'oratio',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '15',
  },
  {
    title: 'ORCA',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '27',
  },
  {
    title: 'OTENAMI Hurricane',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '24',
  },
  {
    title: 'Override',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S',
    hard: 'ep S',
    version: '27',
  },
  {
    title: 'Painful Fate',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '26',
  },
  {
    title: 'Papilio ulysses',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'id B+',
    version: '25',
  },
  {
    title: 'PARADISE LOST',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '18',
  },
  {
    title: 'PARANOiA ～HADES～',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'id A',
    version: '15',
  },
  {
    title: 'Pārvatī',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep D',
    version: '28',
  },
  {
    title: 'Peaktime Booster',
    difficulty: 'ANOTHER',
    normal: 'id B+',
    hard: 'id A',
    version: '30',
  },
  {
    title: 'perditus†paradisus',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '18',
  },
  {
    title: 'Persephone',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '25',
  },
  {
    title: 'Phoenix',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S',
    hard: 'ep S',
    version: '19',
  },
  {
    title: 'Plan 8',
    difficulty: 'ANOTHER',
    normal: 'id S+',
    hard: 'id S+',
    version: '20',
  },
  {
    title: 'PLASMA SOUL NIGHT feat. Nana Takahashi / 709sec.',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '29',
  },
  {
    title: "PLEASE DON'T GO",
    difficulty: 'ANOTHER',
    normal: 'id D',
    hard: 'id D',
    version: '8',
  },
  {
    title: 'Please Welcome Mr.C',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep D',
    version: '26',
  },
  {
    title: 'POSSESSION',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'id C',
    version: '23',
  },
  {
    title: 'Primitive Vibes',
    difficulty: 'ANOTHER',
    normal: 'ep F',
    hard: 'ep F',
    version: '27',
  },
  {
    title: 'Proof of the existence',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '20',
  },
  {
    title: 'PUNISHER',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '21',
  },
  {
    title: 'Purple Perplex',
    difficulty: 'ANOTHER',
    normal: 'id A',
    hard: 'id A+',
    version: '29',
  },
  {
    title: 'Push on Beats!～音ゲの国のeX-ストリーマー～',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '29',
  },
  {
    title: 'Quakes',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '24',
  },
  {
    title: 'QUANTUM TELEPORTATION',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B',
    hard: 'ep B',
    version: '19',
  },
  {
    title: 'quaver♪',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '19',
  },
  {
    title: 'quell～the seventh slave～',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '17',
  },
  {
    title: "ra'am",
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'id B+',
    version: '21',
  },
  {
    title: 'rage against usual',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'id A',
    version: '12',
  },
  {
    title: 'RAGE feat.H14 of LEONAIR',
    difficulty: 'ANOTHER',
    normal: 'id S+',
    hard: 'id S+',
    version: '29',
  },
  {
    title: 'RAIN',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep D',
    version: '24',
  },
  {
    title: 'Rampage',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '25',
  },
  {
    title: 'Raspberry Railgun',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '25',
  },
  {
    title: 'Rave Cannon',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '24',
  },
  {
    title: 'Rave*it!! Rave*it!!',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'id A+',
    version: '22',
  },
  {
    title: 'Rave Patroller',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep D',
    version: '27',
  },
  {
    title: 'RED ZONE',
    difficulty: 'LEGGENDARIA',
    normal: 'ep E',
    hard: 'ep E',
    version: '11',
  },
  {
    title: 'Red. by Full Metal Jacket',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'id A',
    version: '17',
  },
  {
    title: 'Red. by Jack Trance',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id S',
    version: '26',
  },
  {
    title: 'Reflux',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id A+',
    version: '22',
  },
  {
    title: 'refrain',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '23',
  },
  {
    title: 'reunion',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep A',
    version: '18',
  },
  {
    title: 'REVOLVER',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A+',
    hard: 'id S',
    version: '25',
  },
  {
    title: 'RINИE',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '30',
  },
  {
    title: 'Ristaccia',
    difficulty: 'ANOTHER',
    normal: 'ep F',
    hard: 'ep F',
    version: '15',
  },
  {
    title: 'rommmo',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '28',
  },
  {
    title: 'ruin of opals',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '26',
  },
  {
    title: 'sakura storm',
    difficulty: 'ANOTHER',
    normal: 'id F',
    hard: 'id E',
    version: '18',
  },
  {
    title: 'SAMURAI-Scramble',
    difficulty: 'LEGGENDARIA',
    normal: 'id S+',
    hard: 'id S+',
    version: '24',
  },
  {
    title: 'SAY BAY',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '24',
  },
  {
    title: 'Say YEEEAHH',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '22',
  },
  {
    title: 'SCREAM SQUAD',
    difficulty: 'ANOTHER',
    normal: 'id E',
    hard: 'id E',
    version: '12',
  },
  {
    title: 'SCREW // owo // SCREW',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id A+',
    version: '27',
  },
  {
    title: 'Scripted Connection⇒ A mix',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'id C',
    version: '12',
  },
  {
    title: 'Scripted Connection⇒ A mix',
    difficulty: 'LEGGENDARIA',
    normal: 'id A',
    hard: 'ep A',
    version: '12',
  },
  {
    title: 'Secrets',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep A+',
    version: '16',
  },
  {
    title: 'Sense 2007',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'id B',
    version: '14',
  },
  {
    title: 'Session 9-Chronicles-',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '18',
  },
  {
    title: 'Shooting Fireball',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '22',
  },
  {
    title: 'Sigmund',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '21',
  },
  {
    title: 'Sigmund',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S+',
    hard: 'ep S+',
    version: '21',
  },
  {
    title: 'Silver Bullet',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '29',
  },
  {
    title: 'Sinus Iridum',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S+',
    version: '28',
  },
  {
    title: 'Skreaming for Salvation',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'id B+',
    version: '29',
  },
  {
    title: 'Sky High',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '24',
  },
  {
    title: 'Slipstream',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '25',
  },
  {
    title: 'Smalt #28598F',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep C',
    version: '29',
  },
  {
    title: 'Smashing Wedge',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '27',
  },
  {
    title: 'Snake Stick',
    difficulty: 'ANOTHER',
    normal: 'id B+',
    hard: 'id A+',
    version: '19',
  },
  {
    title: 'Snakey Kung-fu',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'id A',
    version: '24',
  },
  {
    title: 'snow storm',
    difficulty: 'LEGGENDARIA',
    normal: 'ep F',
    hard: 'ep F',
    version: '14',
  },
  {
    title: 'Sol Cosine Job 2',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '20',
  },
  {
    title: 'SOLID STATE SQUAD',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '17',
  },
  {
    title: 'SOLID STATE SQUAD',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep A',
    version: '17',
  },
  {
    title: 'SOLID STATE SQUAD -RISEN RELIC REMIX-',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '28',
  },
  {
    title: 'Somnidiscotheque',
    difficulty: 'ANOTHER',
    normal: '',
    hard: '',
    version: '30',
  },
  {
    title: 'Sounds Of Summer',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '22',
  },
  {
    title: 'SpaceLand☆TOYBOX',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '22',
  },
  {
    title: 'SPECIAL SUMMER CAMPAIGN!',
    difficulty: 'ANOTHER',
    normal: 'ep F',
    hard: 'ep F',
    version: '18',
  },
  {
    title: 'spiral galaxy',
    difficulty: 'LEGGENDARIA',
    normal: 'ep C',
    hard: 'ep D',
    version: '11',
  },
  {
    title: 'STARLIGHT DANCEHALL',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '23',
  },
  {
    title: 'Steel Edge',
    difficulty: 'ANOTHER',
    normal: 'id E',
    hard: 'ep E',
    version: '24',
  },
  {
    title: 'STEEL NEEDLE',
    difficulty: 'LEGGENDARIA',
    normal: 'id A',
    hard: 'ep S',
    version: '15',
  },
  {
    title: 'StrayedCatz',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '23',
  },
  {
    title: 'STULTI',
    difficulty: 'ANOTHER',
    normal: 'id B+',
    hard: 'ep B+',
    version: '20',
  },
  {
    title: 'Summerlights(IIDX Edition)',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep D',
    version: '24',
  },
  {
    title: 'Super Freak',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '30',
  },
  {
    title: 'Super Rush',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '24',
  },
  {
    title: 'Sweet Clapper',
    difficulty: 'LEGGENDARIA',
    normal: 'ep E',
    hard: 'ep E',
    version: '24',
  },
  {
    title: 'Symmetry',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '22',
  },
  {
    title: 'SYNC-ANTHEM',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B',
    version: '20',
  },
  {
    title: 'T-REX vs Velociraptor (In the Far east euphoria)',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '27',
  },
  {
    title: 'TECHNO Style Essentials',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '27',
  },
  {
    title: 'TECHNOPHOBIA',
    difficulty: 'ANOTHER',
    normal: 'id A',
    hard: 'ep A+',
    version: '30',
  },
  {
    title: 'THANK YOU FOR PLAYING',
    difficulty: 'LEGGENDARIA',
    normal: 'ep C',
    hard: 'ep B',
    version: '16',
  },
  {
    title: 'THE BRAVE MUST DIE',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '27',
  },
  {
    title: 'The Chase',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id S',
    version: '25',
  },
  {
    title: 'The Clown of 24stairs',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '30',
  },
  {
    title: 'THE DAY OF JUBILATIONS',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '26',
  },
  {
    title: 'THE DEEP STRIKER',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B',
    hard: 'ep B',
    version: '15',
  },
  {
    title: 'THE F∀UST',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '26',
  },
  {
    title: 'The Least 100sec',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '22',
  },
  {
    title: 'The Limbo',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B',
    version: '19',
  },
  {
    title: 'The Limbo',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S+',
    hard: 'ep S',
    version: '19',
  },
  {
    title: 'THE PEERLESS UNDER HEAVEN',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id S',
    version: '28',
  },
  {
    title: 'The Rebellion of Sequencer',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '26',
  },
  {
    title: 'The Sampling Paradise',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '19',
  },
  {
    title: "Thor's Hammer",
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id S+',
    version: '20',
  },
  {
    title: 'thunder HOUSE NATION Remix',
    difficulty: 'LEGGENDARIA',
    normal: 'ep C',
    hard: 'ep C',
    version: '16',
  },
  {
    title: 'Thunderbolt',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '19',
  },
  {
    title: 'TIEFSEE',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '22',
  },
  {
    title: 'Tiempo Loco',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '28',
  },
  {
    title: 'Time to Air',
    difficulty: 'LEGGENDARIA',
    normal: 'id S',
    hard: 'id S',
    version: '15',
  },
  {
    title: 'Timepiece phase II',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '20',
  },
  {
    title: 'Timepiece phase II(CN Ver.)',
    difficulty: 'ANOTHER',
    normal: 'id S',
    hard: 'id S+',
    version: '20',
  },
  {
    title: 'TITANS RETURN',
    difficulty: 'LEGGENDARIA',
    normal: 'id A+',
    hard: 'id S',
    version: '19',
  },
  {
    title: 'Todestrieb',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep D',
    version: '19',
  },
  {
    title: 'TOGAKUSHI',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'id B',
    version: '24',
  },
  {
    title: 'TOMAHAWK',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id A+',
    version: '29',
  },
  {
    title: 'TOXIC VIBRATION',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '22',
  },
  {
    title: 'TRANOID',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S',
    hard: 'ep S',
    version: '14',
  },
  {
    title: 'Trill auf G',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep B+',
    version: '26',
  },
  {
    title: 'Triple Cross',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '29',
  },
  {
    title: 'Triple Counter',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '23',
  },
  {
    title: 'TRIUMPH',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '27',
  },
  {
    title: 'TROOPERS',
    difficulty: 'ANOTHER',
    normal: 'id E',
    hard: 'id E',
    version: '15',
  },
  {
    title: 'True Blue',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '20',
  },
  {
    title: 'Twelfth Style',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '12',
  },
  {
    title: 'Übertreffen',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B',
    hard: 'ep B+',
    version: '15',
  },
  {
    title: 'Umbral',
    difficulty: 'LEGGENDARIA',
    normal: 'ep D',
    hard: 'ep C',
    version: '24',
  },
  {
    title: 'Unbelief',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep A+',
    version: '26',
  },
  {
    title: 'V',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '5',
  },
  {
    title: 'Valanga',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '20',
  },
  {
    title: 'VANESSA',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep D',
    version: '14',
  },
  {
    title: 'VANESSA',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A+',
    hard: 'ep S',
    version: '14',
  },
  {
    title: 'Venom',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '24',
  },
  {
    title: 'Verflucht',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A+',
    version: '21',
  },
  {
    title: 'Verflucht',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S+',
    hard: 'ep S+',
    version: '21',
  },
  {
    title: 'Vinculum stellarum',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '27',
  },
  {
    title: 'Violet Pulse',
    difficulty: 'LEGGENDARIA',
    normal: '',
    hard: '',
    version: '23',
  },
  {
    title: 'Viridian',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '28',
  },
  {
    title: 'Visterhv',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '26',
  },
  {
    title: 'Vitrum',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '28',
  },
  {
    title: 'VOLAQUAS',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '30',
  },
  {
    title: 'voltississimo',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A+',
    version: '26',
  },
  {
    title: 'VOX UP',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'id A+',
    version: '21',
  },
  {
    title: 'Watch Out Pt.2',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'id A',
    version: '18',
  },
  {
    title: 'waxing and wanding',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep A',
    version: '13',
  },
  {
    title: "We're so Happy(P*Light Remix) IIDX ver.",
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B+',
    version: '22',
  },
  {
    title: 'Welcome',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B',
    hard: 'ep B+',
    version: '23',
  },
  {
    title: 'WHA',
    difficulty: 'ANOTHER',
    normal: 'id S',
    hard: 'id S',
    version: '29',
  },
  {
    title: 'WONDER WALKER',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '19',
  },
  {
    title: 'X',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '23',
  },
  {
    title: 'Xerulean',
    difficulty: 'ANOTHER',
    normal: '',
    hard: '',
    version: '30',
  },
  {
    title: 'Xlø',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep A',
    version: '26',
  },
  {
    title: 'Xperanza',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep A',
    version: '25',
  },
  {
    title: 'Y&Co. is dead or alive',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'id S',
    version: '16',
  },
  {
    title: 'YAKSHA',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '19',
  },
  {
    title: 'Ypsilon',
    difficulty: 'LEGGENDARIA',
    normal: 'ep C',
    hard: 'ep D',
    version: '27',
  },
  {
    title: 'ZEPHYRANTHES',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep A',
    version: '23',
  },
  {
    title: 'Zirkfied',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'ep A+',
    version: '20',
  },
  {
    title: 'ZZ',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'ep D',
    version: '22',
  },
  {
    title: '-65℃',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '28',
  },
  {
    title: '199024club -Re:BounceKiller-',
    difficulty: 'ANOTHER',
    normal: 'id A',
    hard: 'id A',
    version: '23',
  },
  {
    title: '2 Beasts Unchained',
    difficulty: 'ANOTHER',
    normal: 'id A',
    hard: 'ep A',
    version: '29',
  },
  {
    title: '255',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'id A+',
    version: '25',
  },
  {
    title: '3!dolon Forc3',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '28',
  },
  {
    title: '3y3s',
    difficulty: 'ANOTHER',
    normal: 'id A',
    hard: 'ep S+',
    version: '16',
  },
  {
    title: '二人ノ廃城幽踊宴',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A+',
    version: '28',
  },
  {
    title: '天邪鬼',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '29',
  },
  {
    title: '紫陽花 -AZISAI-',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '23',
  },
  {
    title: 'バッド・スイーツ、バッド・ドリーム',
    difficulty: 'ANOTHER',
    normal: 'id A',
    hard: 'id A+',
    version: '28',
  },
  {
    title: 'アストライアの双皿',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'id B',
    version: '20',
  },
  {
    title: '紅牡丹',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '22',
  },
  {
    title: '刃図羅',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '24',
  },
  {
    title: 'お菓子の王国',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A+',
    version: '26',
  },
  {
    title: '子供の落書き帳',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B+',
    version: '19',
  },
  {
    title: '抱きしめてモナムール',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '26',
  },
  {
    title: 'デモーニッシュ',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A+',
    hard: 'ep A',
    version: '29',
  },
  {
    title: 'シムルグの目醒め',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '25',
  },
  {
    title: '龍と少女とデコヒーレンス',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B',
    hard: 'ep B',
    version: '20',
  },
  {
    title: 'ディスコルディア',
    difficulty: 'ANOTHER',
    normal: 'id S',
    hard: 'ep S+',
    version: '28',
  },
  {
    title: '童話回廊',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep C',
    version: '24',
  },
  {
    title: '栄冠のカンパネラ',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '30',
  },
  {
    title: '駅猫のワルツ',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '23',
  },
  {
    title: '煉獄のエルフェリア',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep S',
    version: '21',
  },
  {
    title: 'ΕΛΠΙΣ',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '20',
  },
  {
    title: 'ΕΛΠΙΣ',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B',
    hard: 'ep B+',
    version: '20',
  },
  {
    title: '魅惑のYUMMYスイーツ',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '27',
  },
  {
    title: '焔極OVERKILL',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '24',
  },
  {
    title: '電人、暁に斃れる。',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '14',
  },
  {
    title: '不沈艦CANDY',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '16',
  },
  {
    title: 'がっつり陰キャ!?怪盗いいんちょの億劫^^;',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '27',
  },
  {
    title: '神のシナリオ',
    difficulty: 'ANOTHER',
    normal: '',
    hard: '',
    version: '30',
  },
  {
    title: '閠槞彁の願い',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '28',
  },
  {
    title: '儚キ戀ノ幻想譚',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '30',
  },
  {
    title: '華爛漫-Flowers-',
    difficulty: 'LEGGENDARIA',
    normal: 'ep C',
    hard: 'ep C',
    version: '15',
  },
  {
    title: 'ハイテックトキオ',
    difficulty: 'LEGGENDARIA',
    normal: 'id C',
    hard: 'id B',
    version: '29',
  },
  {
    title: '焱影',
    difficulty: 'ANOTHER',
    normal: 'id B+',
    hard: 'id B+',
    version: '24',
  },
  {
    title: '卑弥呼',
    difficulty: 'ANOTHER',
    normal: 'ep S+',
    hard: 'ep S+',
    version: '16',
  },
  {
    title: '烽火連天の刃',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'id A',
    version: '29',
  },
  {
    title: 'お米の美味しい炊き方、そしてお米を食べることによるその効果。',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S',
    hard: 'ep S',
    version: '20',
  },
  {
    title: '表裏一体!?怪盗いいんちょの悩み♥',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '22',
  },
  {
    title: '[ ]DENTITY',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '30',
  },
  {
    title: 'イザナミノナゲキ',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '24',
  },
  {
    title: 'カゴノトリ～弐式～',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep E',
    version: '13',
  },
  {
    title: 'Χ-DEN',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S+',
    version: '26',
  },
  {
    title: '少年A',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep D',
    version: '15',
  },
  {
    title: '君のハートにロックオン',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep A+',
    version: '19',
  },
  {
    title: '恋する☆宇宙戦争っ!!',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '19',
  },
  {
    title: '金野火織の金色提言',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A+',
    version: '26',
  },
  {
    title: '黒髪乱れし修羅となりて',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep E',
    version: '18',
  },
  {
    title: '狂イ咲ケ焔ノ華',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '20',
  },
  {
    title: 'キャトられ♥恋はモ～モク',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep A',
    version: '20',
  },
  {
    title: '共鳴遊戯の華',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '22',
  },
  {
    title: '九尾狐夜行',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep D',
    version: '24',
  },
  {
    title: 'ピアノ独奏無言歌 "灰燼"',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id S',
    version: '29',
  },
  {
    title: '疾風迅雷',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '21',
  },
  {
    title: '疾風迅雷',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S+',
    hard: 'ep S+',
    version: '21',
  },
  {
    title: 'リリーゼと炎龍レーヴァテイン',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '22',
  },
  {
    title: '魔法のかくれんぼ',
    difficulty: 'ANOTHER',
    normal: 'id D',
    hard: 'id B',
    version: '28',
  },
  {
    title: '#MAGiCVLGiRL_TRVP_B3VTZ',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '24',
  },
  {
    title: '龍王の霊廟(Mausoleum Of The Primal Dragon)',
    difficulty: 'LEGGENDARIA',
    normal: 'ep C',
    hard: 'ep C',
    version: '26',
  },
  {
    title: '冥',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep S+',
    version: '12',
  },
  {
    title: 'めいさいアイドル☆あいむちゃん♪',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '23',
  },
  {
    title: '禊',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '29',
  },
  {
    title: 'ミラージュ･レジデンス',
    difficulty: 'LEGGENDARIA',
    normal: 'id B',
    hard: 'id B+',
    version: '15',
  },
  {
    title: '嘆きの樹',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '13',
  },
  {
    title: '†渚の小悪魔ラヴリィ～レイディオ†(IIDX EDIT)',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep B+',
    version: '20',
  },
  {
    title: '夏色DIARY - L.E.D.-G STYLE MIX -',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '22',
  },
  {
    title: 'IX',
    difficulty: 'ANOTHER',
    normal: 'ep S',
    hard: 'ep S',
    version: '21',
  },
  {
    title: '音楽',
    difficulty: 'ANOTHER',
    normal: 'id A',
    hard: 'id A+',
    version: '20',
  },
  {
    title: 'ピアノ協奏曲第1番"蠍火"',
    difficulty: 'ANOTHER',
    normal: 'id A',
    hard: 'id A',
    version: '11',
  },
  {
    title: 'ピアノ協奏曲第1番"蠍火" (BlackY Remix)',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '27',
  },
  {
    title: '世界の果てに約束の凱歌を -ReUnion-',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '28',
  },
  {
    title: '恋愛=精度×認識力',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'id A',
    version: '30',
  },
  {
    title: '深淵に捧ぐレクイエム',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '27',
  },
  {
    title: '逆月',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'ep B+',
    version: '29',
  },
  {
    title: '桜',
    difficulty: 'ANOTHER',
    normal: 'id E',
    hard: 'id D',
    version: '8',
  },
  {
    title: 'シュレーディンガーの猫',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '20',
  },
  {
    title: '聖人の塔',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep B',
    version: '19',
  },
  {
    title: '千年ノ理',
    difficulty: 'ANOTHER',
    normal: 'ep E',
    hard: 'ep F',
    version: '22',
  },
  {
    title: '千年ノ理',
    difficulty: 'LEGGENDARIA',
    normal: 'ep S',
    hard: 'ep A+',
    version: '22',
  },
  {
    title: '旋律のドグマ～Misérables～',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '21',
  },
  {
    title: '雪月花',
    difficulty: 'ANOTHER',
    normal: 'id E',
    hard: 'id E',
    version: '10',
  },
  {
    title: '雪上断火',
    difficulty: 'ANOTHER',
    normal: 'id B',
    hard: 'id B+',
    version: '29',
  },
  {
    title: '灼熱Beach Side Bunny',
    difficulty: 'ANOTHER',
    normal: 'id S+',
    hard: 'id S+',
    version: '18',
  },
  {
    title: '灼熱 Pt.2 Long Train Running',
    difficulty: 'ANOTHER',
    normal: 'id S+',
    hard: 'id S+',
    version: '23',
  },
  {
    title: '〆',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '24',
  },
  {
    title: '神謳 -RESONANCE-',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '25',
  },
  {
    title: '少年は空を辿る',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '22',
  },
  {
    title: '最小三倍完全数',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '26',
  },
  {
    title: '即席！脳直★ミュージックシステム',
    difficulty: 'ANOTHER',
    normal: 'ep D',
    hard: 'ep C',
    version: '20',
  },
  {
    title: 'それは花火のような恋',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep B',
    version: '22',
  },
  {
    title: '水鏡の異界',
    difficulty: 'ANOTHER',
    normal: 'id B+',
    hard: 'id A',
    version: '28',
  },
  {
    title: 'スーパー戦湯ババンバーン',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'ep C',
    version: '28',
  },
  {
    title: 'たまゆら',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B',
    version: '20',
  },
  {
    title: '天空の夜明け',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A+',
    version: '19',
  },
  {
    title: '真 地獄超特急 -HELL or HELL-',
    difficulty: 'ANOTHER',
    normal: 'id A+',
    hard: 'id A+',
    version: '23',
  },
  {
    title: '仮想空間の旅人たち',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep B+',
    version: '20',
  },
  {
    title: '轟け！恋のビーンボール！！',
    difficulty: 'ANOTHER',
    normal: 'ep B',
    hard: 'ep B+',
    version: '21',
  },
  {
    title: 'Ōu Legends',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '30',
  },
  {
    title: '東京神話',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep A+',
    version: '25',
  },
  {
    title: 'トリカゴノ鳳凰',
    difficulty: 'ANOTHER',
    normal: 'ep C',
    hard: 'ep C',
    version: '20',
  },
  {
    title: '津軽雪',
    difficulty: 'ANOTHER',
    normal: 'ep B+',
    hard: 'ep A',
    version: '24',
  },
  {
    title: '∀',
    difficulty: 'ANOTHER',
    normal: 'ep A+',
    hard: 'ep A+',
    version: '28',
  },
  {
    title: '廿',
    difficulty: 'LEGGENDARIA',
    normal: 'ep B',
    hard: 'id B+',
    version: '21',
  },
  {
    title: '伐折羅-vajra-',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '28',
  },
  {
    title: '華麗なる大犬円舞曲',
    difficulty: 'ANOTHER',
    normal: 'ep A',
    hard: 'ep A',
    version: '27',
  },
  {
    title: 'ワルツ第17番 ト短調"大犬のワルツ"',
    difficulty: 'ANOTHER',
    normal: 'id D',
    hard: 'id B',
    version: '17',
  },
  {
    title: '超青少年ノ為ノ超多幸ナ超古典的超舞曲',
    difficulty: 'LEGGENDARIA',
    normal: 'ep A',
    hard: 'ep A+',
    version: '22',
  },
  {
    title: '海神',
    difficulty: 'ANOTHER',
    normal: 'id C',
    hard: 'id C',
    version: '21',
  },
  {
    title: 'ぞうしょく！？マイデンティティ',
    difficulty: 'ANOTHER',
    normal: '',
    hard: '',
    version: '30',
  },
];
